### ISSUE TITLE
Please include xdebug

### ISSUE THREAD

**Issue by jeremyandrews** [tag1consulting/puppet-centos#9]
Drupal 8 has become much more complex, and a debugger has become necessary.

I installed it on my local VM as follows:

```
sudo yum install php56u-devel
sudo yum install php-devel
```

After which it tells me:

```
You should add "zend_extension=/usr/lib64/php/modules/xdebug.so" to php.ini
```

**Comment by jeremyandrews** [comment]
Although reading more carefully, I see this earlier:

```
  |   NOTE: Please disregard the message                                 |
  |       You should add "extension=xdebug.so" to php.ini                |
  |   that is emitted by the PECL installer. This does not work for      |
  |   Xdebug.                                                            |
```

**Comment by jeffsheltren** [comment]
There's actually a php56u-xdebug package, so that should work (without need for installing the -devel package and installing via PECL).  And that also likely configures the .ini file for us.  Let me know if there's any other config/setup needed to get it working.

**Comment by jeffsheltren** [comment]
I pushed da61d4b to include the php xdebug package.  Let me know if we need to do any additional configuration to get xdebug working properly.
